### PR TITLE
Add more debugging information to ``RavenFactory.ravenInstance``.

### PR DESCRIPTION
**Pull request by bretthoerner**
#183 

Used to provide this:

```
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Couldn't create a raven instance for 'Dsn{uri=http://localhost:9999/}'
	at com.getsentry.raven.RavenFactory.ravenInstance(RavenFactory.java:100)
	at com.getsentry.example.Application.main(Application.java:16)
	... 6 more
```

Now provides output like this:

```
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Couldn't create a raven instance for: 'Dsn{uri=http://localhost:9999/}'; ravenFactoryName: com.getsentry.example.TestFactory; skipped factories: com.getsentry.raven.DefaultRavenFactory; tried factories: com.getsentry.example.TestFactory; cause contains exception thrown by the last factory tried.
	at com.getsentry.raven.RavenFactory.ravenInstance(RavenFactory.java:148)
	at com.getsentry.example.Application.main(Application.java:16)
	... 6 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.getsentry.example.TestFactory.createRavenInstance(TestFactory.java:10)
	at com.getsentry.raven.RavenFactory.ravenInstance(RavenFactory.java:103)
	... 7 more
```

---
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-java/229)

### CODE REVIEW

**Comment by tkaemming** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[raven/src/main/java/com/getsentry/raven/RavenFactory.java, line 102 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/229#-KN43IuUv1shwDVY-lG0:-KN43IuUv1shwDVY-lG1:-593156875) ([raw file](https://github.com/getsentry/raven-java/blob/193d936f163e62795fb2c7bc2d3f8417beee557f/raven/src/main/java/com/getsentry/raven/RavenFactory.java#L102)):*
> ```Java
>             logger.debug("Attempting to use '{}' as a Raven factory.", ravenFactory);
>             try {
>                 triedFactories.add(name);
> ```

Does this need to be in the `try` block?

---

*[raven/src/main/java/com/getsentry/raven/RavenFactory.java, line 112 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/229#-KN4475JuZxWn3SloFdh:-KN4475JuZxWn3SloFdi:5172980) ([raw file](https://github.com/getsentry/raven-java/blob/193d936f163e62795fb2c7bc2d3f8417beee557f/raven/src/main/java/com/getsentry/raven/RavenFactory.java#L112)):*
> ```Java
>         }
> 
>         // Throw an IllegalStateException that attempts to be helpful.
> ```

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/229)*

**Comment by tkaemming** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/229)*

**Comment by bretthoerner** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[raven/src/main/java/com/getsentry/raven/RavenFactory.java, line 102 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/229#-KN43IuUv1shwDVY-lG0:-KNCvyUVKZll_mRWnjR-:555362507) ([raw file](https://github.com/getsentry/raven-java/blob/193d936f163e62795fb2c7bc2d3f8417beee557f/raven/src/main/java/com/getsentry/raven/RavenFactory.java#L102)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> Does this need to be in the `try` block?
</details>
Whoops, nope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/229)*

**Comment by tkaemming** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/229)*

**Pull request merged**
