### PR TITLE
Add ContextManager interface so that the idea of 'current context' ca…

### PR DESCRIPTION
**Pull request by bretthoerner**
…n be swapped out.

This is a branch off of `8.0`, it won't land on `master` until we merge `8.0`.

I've paused for a spot-check review before doing more documentation here.

---

On `master` the implementation of a Context is hardcoded to be 1:1 with a thread. In addition, it has the idea of "active" contexts which allow for a single thread to have multiple live contexts. This was taken from the Python SDK and after discussing with @dcramer and @mitsuhiko they both said this functionality wasn't important or useful (please correct me if I'm wrong...).

So, this PR:

* Adds a [ContextManager](https://github.com/getsentry/raven-java/blob/19643071c0ef2a6df610d2819a3f81fc02f7176c/raven/src/main/java/com/getsentry/raven/context/ContextManager.java) interface for the base type where `Context` used to be hardcoded, every `Raven` instance will need to pick an impl.
* Adds a [ThreadLocalContextManager](https://github.com/getsentry/raven-java/blob/19643071c0ef2a6df610d2819a3f81fc02f7176c/raven/src/main/java/com/getsentry/raven/context/ThreadLocalContextManager.java) contains the "old' implementation, and the one you'd want to use when using (for example) a 1:1 thread:request webserver.
* Adds a [SingletonContextManager](https://github.com/getsentry/raven-java/blob/19643071c0ef2a6df610d2819a3f81fc02f7176c/raven/src/main/java/com/getsentry/raven/context/SingletonContextManager.java) for having 1 `Context` object for the entire application, which is [used by default on Android](https://github.com/getsentry/raven-java/blob/19643071c0ef2a6df610d2819a3f81fc02f7176c/raven-android/src/main/java/com/getsentry/raven/android/AndroidRavenFactory.java#L66) so that `Breadcrumb`s from any thread go to the same ringbuffer, `User` only needs to be set once for all threads, etc.
* Creates a `context` package and renamed `RavenContext` (bleh) to `Context` since we're breaking everything anyway. To be fair users shouldn't have been using that class directly anyway.

I'm struggling with how users should decide which implementation to use. 
* Do we stick with default `ThreadLocalContextManager` and they have to override the factory to switch impl choice?
* Do we default to a `null` `ContextManager` and noop everything until they configure it?
* Should the impl be chosen in the DSN?
* Can we make any decisions on which impl to use automatically?
* In the future if we have `raven-servlet`, `raven-netty`, `raven-finagle`, `raven-spring` etc artifacts -- will this API support configuring and handling the contexts as they differ between each of these?

### CODE REVIEW

**Comment by bretthoerner** [comment]
This also replaces #302, since Contexts don't have to activated before you can add breadcrumbs.

**Comment by bretthoerner** [comment]
Rebased this.

**Comment by tkaemming** [comment]
> I'm struggling with how users should decide which implementation to use. 
> * Do we stick with default `ThreadLocalContextManager` and they have to override the factory to switch impl choice?

I think this is reasonable.

> * Do we default to a `null` `ContextManager` and noop everything until they configure it?

Nah.

> * Should the impl be chosen in the DSN?

I think this is a good idea.

> * Can we make any decisions on which impl to use automatically?

Yeah, I think we should have reasonable defaults (e.g. how you mentioned Android will default to the singleton) but allow them to be overridden (preferably by DSN, but also by factory) if people really have a strong opinion.

> * In the future if we have `raven-servlet`, `raven-netty`, `raven-finagle`, `raven-spring` etc artifacts -- will this API support configuring and handling the contexts as they differ between each of these?

Would this be any different than Android?

**Comment by bretthoerner** [comment]
> Would this be any different than Android?

I think that some of these may require passing us an actual object. ThreadLocal and Singleton and very simple, but I can imagine (as an example) `raven-finagle` needing some reference to your actual executor pool (or whatever they call it) to "follow" async requests around. So that's not something they can simply set in the DSN. I guess for these weird cases we'll just offer simple `DefaultRavenFactory` subclasses in the package that helps them get started or something? This isn't anything I was planning for soon anyway... I think we're covered OK by the work in this PR.

**Comment by bretthoerner** [comment]
OK @tkaemming docs are filled in. I don't think we need a first-class way to pick an impl until we have more implementations to choose from.

**Pull request merged**
