### PR TITLE
Add filename to `StackTraceInterfaceBinding`.

### PR DESCRIPTION
**Pull request by tkaemming**
Fixes GH-153.

### CODE REVIEW

**Comment by tkaemming** [comment]
This is handled correctly when rendering the stack frace via JavaScript now: https://github.com/getsentry/sentry/blob/38efc3472787c8969f25b33a1e69624979151173/src/sentry/static/sentry/app/components/events/interfaces/rawStacktraceContent.jsx#L74-L90

This is also handled correctly on the backend when rendering a stack frame: https://github.com/getsentry/sentry/blob/38efc3472787c8969f25b33a1e69624979151173/src/sentry/templates/sentry/partial/frames/java.txt

**Comment by tkaemming** [comment]
Just kidding, the backend implementation is still incorrect — I'll fix that also.

**Comment by tkaemming** [comment]
This is fixed on the server now and should be ready to go: https://github.com/getsentry/sentry/pull/2349

**Comment by mikelikespie** [comment]
Thanks for fixing this!

**Pull request merged**
