### PR TITLE
Logback: Add the possibility to supply User information through MDC

### PR DESCRIPTION
**Pull request by mpecan**
Changes:
* Added properties to allow for the definition of keys in the MDC that will be used to retrieve user information
* In case the keys are set and there is data the Appender will add an instance of UserInterface to the EventBuilder
* The data that has been added to the UserInterface will not be added to ExtraInfo

The fields might be not be optimally named and I am open to any suggestions there (or anywhere else for that matter, I was not able to find much information about contribution guidelines - the Sentry ones were not much help here).

### CODE REVIEW

**Comment by bretthoerner** [comment]
Thanks for this, I definitely want something similar. The two issues I see are:

1. We like to maintain feature parity between all logging backends, so I'll need to make this work for the others.
2. I wonder if the MDC style is too "heavy" -- we probably want to do this for more than just the User interface. I need to think about easier ways to do this, but maybe MDC is the only way?

**Comment by mpecan** [comment]
1. I am more than willing to make it work for the other backends when the pattern is established for one
2. I am unsure of another style to use here instead. Introducing an additional ThreadLocal instance for user storage seems too heavy handed. The MDC is meant to convey the context of the thread (thus the user is also part of the context), so that was why I used it here.

We currently have an incompatible and less generic solution in use in our project (we only used one MDC field for the whole user) and this one seems more flexible and less problematic. 

Using a ThreadLocal instance might be viable, as it would allow for a "User" interface to be passed instead. I can do an exploratory branch for a ThreadLocal option if you want. The MDC does limit you to passing strings which might be a detriment here.

**Comment by bretthoerner** [comment]
So we have the notion of a `Context`, it hasn't been put to much use outside of `Breadcrumb`s yet: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/RavenContext.java

We could add a real `User` class that could be set on the `Context` and pulled out when events are built?

**Comment by mpecan** [comment]
I will try that out. Thanks for the pointer.

**Comment by mpecan** [comment]
Superseded by: #303

**Pull request closed without merging**
