### PR TITLE
Add formatted field to JSON if possible.

### PR DESCRIPTION
**Pull request by bretthoerner**
Done more correctly this time.

It's not setup for log4j yet. I've never understood how (or if) log4j supports parameterized log messages. I guess *maybe* `message` can be of type `ParameterizedMessage`? But I think we'd be failing today if that were true.

The most common pattern seems to be,

```
if logging at this level is enabled:
    log(manually_format(msg))
```

So maybe in log4j we just always send `message` as `formatted` (no params)? We can also leave out `formatted` on log4j.

---
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-java/220)

### CODE REVIEW

**Comment by tkaemming** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java, line 120 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KMREZsl0-9xwVLRs8P8:-KMREZsmOIWFJzj8MiFo:262468467) ([raw file](https://github.com/getsentry/raven-java/blob/dcc9aa74661eca9a822437a37ded2bfe878664ef/raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java#L120)):*
> ```Java
>         return Objects.equals(message, that.message)
>             && Objects.equals(parameters, that.parameters)
>             && Objects.equals(formatted, that.formatted);
> ```

:thumbsup: 

---

*[raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java, line 232 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KMRG85hmnkvxWO8x3bw:-KMRG85hmnkvxWO8x3bx:-145123204) ([raw file](https://github.com/getsentry/raven-java/blob/dcc9aa74661eca9a822437a37ded2bfe878664ef/raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java#L232)):*
> ```Java
>                 } catch (MissingFormatArgumentException e) {
>                     // use unformatted message
>                     formatted = message;
> ```

If formatting fails here, I think it might make sense to pass the parameters through but *not* format the message?

So:

1. If `parameters` is null, don't format (`null` value for `formatted` parameter to the `MessageInterface` constructor).
2. If formatting succeeds (including if the `parameter` collection is empty — but *not* null), use that as the `formatted` constructor parameter to `MessageInterface` and event `message` attribute.
3. If formatting fails (wrong number of params, bad `toString` call, any other reason), use a `null` value for the `formatted` constructor parameter, and use the "raw" message for the event `message` attribute.

Does this seem reasonable?

---

*[raven/src/main/java/com/getsentry/raven/marshaller/json/MessageInterfaceBinding.java, line 44 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KMRDHzik-bStbaI5WPm:-KMRDHzik-bStbaI5WPn:435599615) ([raw file](https://github.com/getsentry/raven-java/blob/dcc9aa74661eca9a822437a37ded2bfe878664ef/raven/src/main/java/com/getsentry/raven/marshaller/json/MessageInterfaceBinding.java#L44)):*
> ```Java
>         generator.writeEndArray();
>         if (messageInterface.getFormatted() != null) {
>             generator.writeStringField(FORMATTED_PARAMETER, formatMessage(messageInterface.getFormatted()));
> ```

It wasn't introduced here, but the name `formatMessage` threw me for a second. `trimMessage` might be better.,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/220)*

**Comment by bretthoerner** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java, line 232 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KMRG85hmnkvxWO8x3bw:-KMe-9eHwaQaMpFnAs1N:1420942927) ([raw file](https://github.com/getsentry/raven-java/blob/dcc9aa74661eca9a822437a37ded2bfe878664ef/raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java#L232)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> If formatting fails here, I think it might make sense to pass the parameters through but *not* format the message?
> 
> So:
> 
> 1. If `parameters` is null, don't format (`null` value for `formatted` parameter to the `MessageInterface` constructor).
> 2. If formatting succeeds (including if the `parameter` collection is empty — but *not* null), use that as the `formatted` constructor parameter to `MessageInterface` and event `message` attribute.
> 3. If formatting fails (wrong number of params, bad `toString` call, any other reason), use a `null` value for the `formatted` constructor parameter, and use the "raw" message for the event `message` attribute.
> 
> Does this seem reasonable?
</details>
OK, refactored some to handle all of those cases.

* I'm not in love with `topLevelMessage` var/name but I can't think of a cleaner way to handle it right now. We have 3 versions: `message` (original), `formatted`, and `topLevelMessage` which is sort of like "maybe formatted, maybe not".
* I'm using a deprecated method, I'm not sure if we actually want it to be deprecated though: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java#L40

Without calling that, there will be no `sentry.interfaces.Message`added to the object. Your comment implies we always want to send the interface, right?

---

*[raven/src/main/java/com/getsentry/raven/marshaller/json/MessageInterfaceBinding.java, line 44 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KMRDHzik-bStbaI5WPm:-KMdlY5LvNA79Ozq22HW:-499146009) ([raw file](https://github.com/getsentry/raven-java/blob/dcc9aa74661eca9a822437a37ded2bfe878664ef/raven/src/main/java/com/getsentry/raven/marshaller/json/MessageInterfaceBinding.java#L44)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> It wasn't introduced here, but the name `formatMessage` threw me for a second. `trimMessage` might be better.,
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/220)*

**Comment by tkaemming** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGES, line 6 \[r3\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KN508E43mF4pJ-6Baka:-KN508E43mF4pJ-6Bakb:177553207) ([raw file](https://github.com/getsentry/raven-java/blob/2fbc25c89de73037a13140e1f9f1e6544ad91641/CHANGES#L6)):*
> ```
> - Changed default ``raven.async.queuesize`` from unlimited to 50.
> - Add ``formatted`` field to JSON payload if possible.
> - Add callback system for exceptions raised while attempting to send events.
> ```

Not sure why this is showing as updated in the review…

---

*[raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java, line 232 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KMRG85hmnkvxWO8x3bw:-KN5-689BmZso90id5sr:375743915) ([raw file](https://github.com/getsentry/raven-java/blob/dcc9aa74661eca9a822437a37ded2bfe878664ef/raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java#L232)):*
I think this makes sense.

> I'm using a deprecated method, I'm not sure if we actually want it to be deprecated though: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java#L40

Hm... yeah, I don't think that should be deprecated any more.

> Your comment implies we always want to send the interface, right?

Yeah, I think so. (That is my understanding of how it should work, at least.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/220)*

**Comment by bretthoerner** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGES, line 6 \[r3\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KN508E43mF4pJ-6Baka:-KNCyciWP6MAPmBF2RRA:611509222) ([raw file](https://github.com/getsentry/raven-java/blob/2fbc25c89de73037a13140e1f9f1e6544ad91641/CHANGES#L6)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> Not sure why this is showing as updated in the review…
</details>
Yeah, I moved this up to 7.5.0 regardless, looks fine on Github.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/220)*

**Comment by tkaemming** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java, line 40 \[r4\]](https://reviewable.io:443/reviews/getsentry/raven-java/220#-KNDSq5xr_TduHu7rf19:-KNDSq5yQ3W1k2ByvUs3:1319255877) ([raw file](https://github.com/getsentry/raven-java/blob/59c9ea82ec4b97d0ae90c79637b0c7e1a729421c/raven/src/main/java/com/getsentry/raven/event/interfaces/MessageInterface.java#L40)):*
> ```Java
>      * <p>
>      * While it's technically possible to create a non parametrised message with {@code MessageInterface}, it's
>      * recommended to use {@link com.getsentry.raven.event.EventBuilder#withMessage(String)} instead.
> ```

I don't think this comment is accurate any longer either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/220)*

**Pull request merged**
