### PR TITLE
Add serverName override to logging SentryAppenders

### PR DESCRIPTION
**Pull request by mattbillenstein**

### CODE REVIEW

**Comment by bretthoerner** [comment]
This seems related to https://github.com/getsentry/raven-java/issues/175, where we want to figure out a way to override/discover the server name (for all appenders).

**Comment by tkaemming** [comment]
I like this approach overall.

A few notes:

- for log4j2, I think this requires the `PluginAttribute` parameter annotation,
- we'd also want to add this to `raven.jul.SentryHandler` before releasing.

**Comment by bretthoerner** [comment]
+1 fixed checkstyle and minor stuff here, could use review: https://github.com/getsentry/raven-java/pull/195

**Comment by bretthoerner** [comment]
Finished this up and merged in https://github.com/getsentry/raven-java/commit/ec69aca36f8bcc4540b47d44f226c837bc78a187

Thanks @mattbillenstein !

**Comment by mattbillenstein** [comment]
Just tried this out and it doesn't seem to work for me -- using log4j and version 7.2.1, I just get the ip address of the machine instead of the server name I set in the config.

**Comment by tkaemming** [comment]
I confirmed this doesn't work for me either against the [log4j example](https://github.com/getsentry/raven-java-examples/tree/master/raven-java-log4j-example) with this configuration patch off of raven-java-examples@9c62895761e949aabf25fc8cd65e0c051bda6b6a:

```diff
diff --git a/raven-java-log4j-example/src/main/resources/log4j.properties b/raven-java-log4j-example/src/main/resources/log4j.properties
index 2251f45..4c54ca4 100644
--- a/raven-java-log4j-example/src/main/resources/log4j.properties
+++ b/raven-java-log4j-example/src/main/resources/log4j.properties
@@ -5,3 +5,4 @@ log4j.appender.Console.layout=org.apache.log4j.PatternLayout
 log4j.appender.Console.layout.ConversionPattern=%d{HH:mm:ss.SSS} [%t] %-5p: %m%n
 
 log4j.appender.Sentry=com.getsentry.raven.log4j.SentryAppender
+log4j.appender.Sentry.serverName=customhost
```

I'm going to close this again, though (opening the pull request itself doesn't make a lot of sense) and reopen #175.

**Comment by tkaemming** [comment]
Actually, we don't have to reopen #175. I just tested `7.2.2-SNAPSHOT`, which works correctly. 19fc9e32dbf078b2261a45264ffdce28f0fdcaaa added the missing `setServerName` mutator.

We'll promote that to `7.2.2` later today. Sorry!

**Comment by mattbillenstein** [comment]
Ah, cool, thanks -- I'll retest once this is pushed later on then.

**Comment by bretthoerner** [comment]
Sorry about that, it's been released to Maven central and should be synced everywhere within a few hours.

**Comment by mattbillenstein** [comment]
No worries -- confirmed 7.2.2 works.  Thanks much!

**Pull request closed without merging**
