### PR TITLE
support for "release" event property

### PR DESCRIPTION
**Pull request by galmeida**
- support for sending events with release property
- support for release property on raven-logback.

### CODE REVIEW

**Comment by dcramer** [comment]
Looks good, thanks!

**Comment by pulse00** [comment]
@dcramer when will this be released? The latest version `6.0.0` doesn't contain release support.

**Comment by tkaemming** [comment]
@pulse00 This was released as part of version 7.0.0, which also changes the `groupId` to `com.getsentry`: https://github.com/getsentry/raven-java/releases/tag/v7.0.0

**Comment by pulse00** [comment]
@tkaemming thanks a lot

**Comment by pulse00** [comment]
@tkaemming regarding this deadlock issue (https://github.com/getsentry/raven-java/issues/151): is this an issue of the 7.0.0 release only, or does it also affect 6.x? In other words: By upgrading to 7.0.0, will we likely hit this problem, so we should rather stay on 6.x until it's solved?

**Comment by bretthoerner** [comment]
@pulse00 The issue existed before 7.0.0. You may want to do the workaround in #151: disable Sentry logging for the `com.getsentry` package.

I'll be looking into the deadlock soon.

**Comment by pulse00** [comment]
great, thanks for clarification.

**Pull request merged**
