### PR TITLE
Drop dependency on Guava.

### PR DESCRIPTION
**Pull request by bretthoerner**
* Drops Guava (duh).
* Added `findbugs`'s `jsr305` (only at compile time) for some annotations (like `Nullable`).
* Created `com.getsentry.raven.util.Util` class with some static helpers.
* Pulled in Base64 input/output stream classes from Android (much simpler than the ones in Guava). Ignored these in checkstyle as its not code we "manage" and the style is very different from ours.

Tests and checkstyle and all that good stuff passing for me.

#196

### CODE REVIEW

**Comment by bretthoerner** [comment]
Working for me with the `raven-java-example` project.

**Comment by bretthoerner** [comment]
@tkaemming did you think this was good to go in after 7.2.0?

**Comment by tkaemming** [comment]
Yeah, a quick skim of this looks good to me (except you'll want to move the changelog entry.)

I'm on the fence as to whether this is significant enough to do another release for this specific change. I don't really think there are a lot of people asking for this specifically, but it might be nice to get some people testing this independent of any other changes?

**Comment by bretthoerner** [comment]
https://github.com/getsentry/raven-java/commit/effd50a2f6088b294e067b6583575395ef99fb29

**Pull request closed without merging**
