### PR TITLE
Rename Sentry to SentryClient, rename android.Sentry to SentryAndroid…

### PR DESCRIPTION
**Pull request by bretthoerner**
…, and add Sentry utility class for all static usage.

Part of #376.

* All static shit will be unambiguously on one class (even for Android, which was an issue before).
* No more collision in names between static and client methods.

Tests pass. I need to check all the docs still.

### CODE REVIEW

**Comment by HazAT** [comment]
- [ ] Remove base64 encoding -> Use simple gzipped JSON

**Comment by bretthoerner** [comment]
@HazAT added the base64 change to the list on #376 so this PR doesn't grow even larger 😁

**Comment by HazAT** [comment]
Added compatibility for new distributions in sentry https://github.com/getsentry/sentry/pull/5262
@bretthoerner sorry probably shouldn't have added it here, but from my side this PR lgtm :shipit:

**Comment by bretthoerner** [comment]
np, moved to #379 ;)

**Pull request merged**
