### PR TITLE
Add static `Raven.capture` methods that send to the most recently con…

### PR DESCRIPTION
**Pull request by bretthoerner**
…structed Raven instance.

As discussed, this is especially important on Android, but will be useful everywhere.

---
This change is [Reviewable](https://reviewable.io/reviews/getsentry/raven-java/236)

### CODE REVIEW

**Comment by bretthoerner** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[raven/src/main/java/com/getsentry/raven/Raven.java, line 135 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNs9tOSk6xfg1HbUUPa:-KNs9tOSk6xfg1HbUUPb:1165071271) ([raw file](https://github.com/getsentry/raven-java/blob/b8529296e22537044cef14030316871335c9ca5c/raven/src/main/java/com/getsentry/raven/Raven.java#L135)):*
> ```Java
>         runBuilderHelpers(eventBuilder);
>         return eventBuilder.build();
>     }
> ```

These `toEvent` methods may look a little odd. I had to pull the logic out so that I could have static methods (`createEvent`... they can't collide on names) that can help me get from any non-Event to an Event (using the statically stored Raven instance, because it may have its own builder helpers etc).

One reason for this is Android, if a user tries to send a `String` message and the internet connection is down, I need to hydrate a full `Event` object so I can cleanly store it on disk for later sending.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Comment by bretthoerner** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[raven/src/main/java/com/getsentry/raven/Raven.java, line 135 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNs9tOSk6xfg1HbUUPa:-KNsAQKcpfLDWme5soGs:552185321) ([raw file](https://github.com/getsentry/raven-java/blob/b8529296e22537044cef14030316871335c9ca5c/raven/src/main/java/com/getsentry/raven/Raven.java#L135)):*
<details><summary><i>Previously, bretthoerner (Brett Hoerner) wrote…</i></summary>
> These `toEvent` methods may look a little odd. I had to pull the logic out so that I could have static methods (`createEvent`... they can't collide on names) that can help me get from any non-Event to an Event (using the statically stored Raven instance, because it may have its own builder helpers etc).
> 
> One reason for this is Android, if a user tries to send a `String` message and the internet connection is down, I need to hydrate a full `Event` object so I can cleanly store it on disk for later sending.
</details>
It's worth noting -- the only reason I "need" to do this is because I can pro-actively detect the internet is down. So I won't even *try* to send events.

We *could* just push everything through the full "create *and* send" logic, letting the send fail and then handle everything there. Android-Sentry currently checks internet connectivity though, and it seemed like a good idea to keep?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Comment by tkaemming** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[CHANGES, line 4 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNsUzUtiGRPKWCpPWDU:-KNsUzUtiGRPKWCpPWDV:1071747332) ([raw file](https://github.com/getsentry/raven-java/blob/b8529296e22537044cef14030316871335c9ca5c/CHANGES#L4)):*
> ```
> -------------
> 
> - Add static `Raven.capture` methods that send to the most recently constructed Raven instance.
> ```

Sort of an aside, but we should decide on single or double backticks here. :)

---

*[raven/src/main/java/com/getsentry/raven/Raven.java, line 51 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNsVcAUqHN-LkkCZ3-t:-KNsVcAUqHN-LkkCZ3-u:-661134683) ([raw file](https://github.com/getsentry/raven-java/blob/b8529296e22537044cef14030316871335c9ca5c/raven/src/main/java/com/getsentry/raven/Raven.java#L51)):*
> ```Java
>      *
>      * @deprecated in favor of {@link Raven#Raven(Connection)} because until you call
>      * {@link Raven#setConnection(Connection)} this instance will throw exceptions when used.
> ```

Good move here. :thumbsup: 

---

*[raven/src/main/java/com/getsentry/raven/Raven.java, line 135 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNs9tOSk6xfg1HbUUPa:-KNsbirD9DP11tImnPzc:1795148042) ([raw file](https://github.com/getsentry/raven-java/blob/b8529296e22537044cef14030316871335c9ca5c/raven/src/main/java/com/getsentry/raven/Raven.java#L135)):*
<details><summary><i>Previously, bretthoerner (Brett Hoerner) wrote…</i></summary>
> It's worth noting -- the only reason I "need" to do this is because I can pro-actively detect the internet is down. So I won't even *try* to send events.
> 
> We *could* just push everything through the full "create *and* send" logic, letting the send fail and then handle everything there. Android-Sentry currently checks internet connectivity though, and it seemed like a good idea to keep?
</details>
(Discussed out of band, but we're going to try and push the offline buffering for Android into a connection implementation.)

---

*[raven/src/main/java/com/getsentry/raven/Raven.java, line 193 \[r2\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNscOH_Wk-DjIx1Xr_8:-KNscOHaegx4uVukbVBH:1903768991) ([raw file](https://github.com/getsentry/raven-java/blob/b46a69a6d08836ad0c237013f4925f38d5b0a25d/raven/src/main/java/com/getsentry/raven/Raven.java#L193)):*
> ```Java
>     // --------------------------------------------------------
> 
>     private static void checkStored() {
> ```

It seems like it might be a little more straightforward to make this `getStored` (`getStoredInstance`, even?) returning `Raven` instead of `void` and chaining the `send*` calls off of the result.

---

*[raven/src/test/java/com/getsentry/raven/RavenTest.java, line 179 \[r2\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNsdvu44tDLVNwcbj-c:-KNsdvu5vF3jsKddWVT-:-639671017) ([raw file](https://github.com/getsentry/raven-java/blob/b46a69a6d08836ad0c237013f4925f38d5b0a25d/raven/src/test/java/com/getsentry/raven/RavenTest.java#L179)):*
> ```Java
> 
>     @Test
>     public void testSendEventBuilerStatically() throws Exception {
> ```

`s/Builer/Builder/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Comment by bretthoerner** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGES, line 4 \[r1\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNsUzUtiGRPKWCpPWDU:-KNsg1udPPeJX9tdXYmq:-1167691682) ([raw file](https://github.com/getsentry/raven-java/blob/b8529296e22537044cef14030316871335c9ca5c/CHANGES#L4)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> Sort of an aside, but we should decide on single or double backticks here. :)
</details>
Oops, seems like double everywhere but my last 2 changes, will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Comment by bretthoerner** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[raven/src/main/java/com/getsentry/raven/Raven.java, line 193 \[r2\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNscOH_Wk-DjIx1Xr_8:-KNsirtexzWJw9ReJMEo:-499146009) ([raw file](https://github.com/getsentry/raven-java/blob/b46a69a6d08836ad0c237013f4925f38d5b0a25d/raven/src/main/java/com/getsentry/raven/Raven.java#L193)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> It seems like it might be a little more straightforward to make this `getStored` (`getStoredInstance`, even?) returning `Raven` instead of `void` and chaining the `send*` calls off of the result.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Comment by bretthoerner** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[raven/src/test/java/com/getsentry/raven/RavenTest.java, line 179 \[r2\]](https://reviewable.io:443/reviews/getsentry/raven-java/236#-KNsdvu44tDLVNwcbj-c:-KNsitcWvh0ZspRwaL-X:-499146009) ([raw file](https://github.com/getsentry/raven-java/blob/b46a69a6d08836ad0c237013f4925f38d5b0a25d/raven/src/test/java/com/getsentry/raven/RavenTest.java#L179)):*
<details><summary><i>Previously, tkaemming (ted kaemming) wrote…</i></summary>
> `s/Builer/Builder/`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Comment by tkaemming** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/raven-java/236)*

**Pull request merged**
