### PR TITLE
Capture uncaught exceptions as FATAL level for Android.

### PR DESCRIPTION
**Pull request by tkaemming**

### CODE REVIEW

**Comment by tkaemming** [comment]
This was brought up by a user via support. I'm assuming that an uncaught exception on *any* thread will crash out the application (not just those on the main thread) but I haven't actually tested to verify this. Is that assumption correct?

**Comment by bretthoerner** [comment]
> I'm assuming that an uncaught exception on any thread will crash out the application 

I highly doubt that, I'll check though.

**Comment by tkaemming** [comment]
> I highly doubt that (because it's not what happens in standard Java), I'll check though.

Me too, actually, but I couldn't find anything that mentioned otherwise. 😕

**Comment by bretthoerner** [comment]
So this will work on any thread that doesn't set it own (or isn't in a ThreadGroup that sets its own) uncaught handler... which in my experience is most/all threads. But non-main thread death doesn't kill the process.

It looks like we can detect whether we're in the main thread if we'd like to adjust this to log non-main thread ones as ERROR or something? http://stackoverflow.com/a/11411087/11958

**Comment by bretthoerner** [comment]
Re-reading this, I actually think `FATAL` is a fine error for thread death (even if it doesn't kill the app itself). I'd say we merge this as-is if you agree.

**Comment by bretthoerner** [comment]
jk thought of something small and pushed a small change. :grimacing:

**Pull request merged**
