### PR TITLE
Remote address resolver

### PR DESCRIPTION
**Pull request by bretthoerner**
https://github.com/getsentry/raven-java/issues/164

### CODE REVIEW

**Comment by bretthoerner** [comment]
OK @tkaemming, I think this one is ready for a glance. I didn't add anything to the `README` yet,  I guess we don't have a spot where we talk about having your own `RavenFactory`?

I did go ahead and add an implement for `X-FORWARDED-FOR` (`ForwardedAddressResolver`). Naming is hard, but I think it gives people a starting point if they want to use it today.

**Comment by tkaemming** [comment]
This looks good to me. I'd credit the original author (@j-fernandes) in the commit message and/or `CHANGES`.

> I guess we don't have a spot where we talk about having your own `RavenFactory`?

It's briefly mentioned in the documentation for some of the logging integrations, but yeah — we should probably cover this in the `README`. (It'd probably make sense at least to cover the reasons /why/ you'd want to.)

> I did go ahead and add an implement for X-FORWARDED-FOR (ForwardedAddressResolver). Naming is hard, but I think it gives people a starting point if they want to use it today.

:thumbsup:

**Comment by bretthoerner** [comment]
> This looks good to me. I'd credit the original author (@j-fernandes)

Oops, thought it was you. Fixed.

Added some starter notes about `RavenFactory` in `README`.

https://github.com/getsentry/raven-java/commit/c5f9e2d4f0d2fca8b6d54b520c8aa997bbef1fd7

**Comment by tkaemming** [comment]
> Oops, thought it was you. Fixed.

Nah, I just rearranged some of the code from the original patch. :)

**Pull request closed without merging**
