### PR TITLE
Make Context and User classes serializable

### PR DESCRIPTION
**Pull request by vgarmash**
For custom implementations of ContextManager it is required that Context object can be serialized.

### CODE REVIEW

**Comment by bretthoerner** [comment]
Hmm, why do these need to be serializable? I believe you, but it's not clicking for me. :(

**Comment by bretthoerner** [comment]
Sorry, I just saw your response on support. This does seem like a harmless change but I'm still a little confused as to why you need to serialize the entire Context? Typically in the client the only serialization we do is to write evens to disk if the network is down, and in that case we don't write out the `Context` but rather things like `Breadcrumb`s which are already Serializable.

**Comment by vgarmash** [comment]
I made Context as a session-scoped variable. All objects that we store in web server session should be serializable.

"When your applications stores data in an HTTP session object, the data must be serializable."

https://docs.oracle.com/cd/E13222_01/wls/docs100/webapp/sessions.html

Yes, Breadcrumbs are serializable, but Raven class can read them only from Context. You use ContextManager to access the context object. So I can't just use Breadcrumbs itself but I have to go through your API to deal with them.

To store calls chain between separate pages I have to make ContextManager which will store Context (and Breadcrumbs for that matter) in HTTP Session so when the error happens we will have full trail path and will be able to see what pages user visited before the error happened.

**Comment by bretthoerner** [comment]
Makes sense, thanks!

**Comment by vgarmash** [comment]
Very good. So can you do new release with my change in it or we should wait until your big release with all other changes?

**Comment by bretthoerner** [comment]
I'll do a point release, and then it will also be in `sentry-java` 1.0 soon.

**Comment by bretthoerner** [comment]
@vgarmash Released 8.0.3 to Maven, it'll take a bit to sync.

**Pull request merged**
